server:
    port: 9092

spring:
    profiles:
        active: global

logging:
    level:
        org: INFO
        com: INFO

predix:
    timeseries:
        queryUrl: https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io/v1/datapoints
        zoneid: ed7b290c-bab9-4206-bc5f-ba78ae0dc416
        websocket:
            uri: wss://gateway-predix-data-services.run.aws-usw02-pr.ice.predix.io/v1/stream/messages
            pool:
                maxIdle: 5
                maxActive: 5
                maxWait: 8000
    oauth:
        issuerId:
            url: https://756661d6-dba3-4132-a94d-6445429812ca.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
        clientIdEncode: true
        clientId: client:secret
    asset:
        zoneid: d179568f-417b-4308-bdf3-e9a8e9caf9fc
        restHost: predix-asset.run.aws-usw02-pr.ice.predix.io
        assetSocketTimeout: 40000
        connectionTimeout: 40000

sensor:
    max:
        quality: 4

consumer:
    rest:
        service:
             url: https://predix-asset.run.aws-usw02-pr.ice.predix.io/consumer
    profile:
        rest:
            service:
                url: https://predix-asset.run.aws-usw02-pr.ice.predix.io/consumption

generation:
    profile:
        rest:
            service:
                url: https://predix-asset.run.aws-usw02-pr.ice.predix.io/generation
