server:
    port: 9092

spring:
    profiles:
        active: global

logging:
    level:
        org: INFO
        com: INFO

predix:
    timeseries:
        queryUrl: https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io/v1/datapoints
        zoneid: 8046ff11-9879-46a9-bea5-32e22caae269
        websocket:
            uri: wss://gateway-predix-data-services.run.aws-usw02-pr.ice.predix.io/v1/stream/messages
            pool:
                maxIdle: 5
                maxActive: 5
                maxWait: 8000
    oauth:
        issuerId:
            url: https://01ea0bc3-68f4-4626-849f-d4c70c6620a5.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
        clientIdEncode: true
        clientId: client:secret
    asset:
        zoneid: 607dad95-6743-40b3-a5fe-7188bbc8223d
        restHost: predix-asset.run.aws-usw02-pr.ice.predix.io
        assetSocketTimeout: 40000
        connectionTimeout: 40000

sensor:
    max:
        quality: 4

consumer:
    rest:
        service:
             url: https://predix-asset.run.aws-usw02-pr.ice.predix.io/consumer
    profile:
        rest:
            service:
                url: https://predix-asset.run.aws-usw02-pr.ice.predix.io/consumption

generation:
    profile:
        rest:
            service:
                url: https://predix-asset.run.aws-usw02-pr.ice.predix.io/generation
